/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7C5BZRRjfgg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function WeatherComponent() {
  return (
    <div className="border rounded-lg w-full">
      <div className="relative w-full overflow-auto">
        <Table>
          <TableHeader>
            <TableRow className="bg-red-500">
              <TableHead className="w-[100px] font-bold text-white">Viikko</TableHead>
              <TableHead className="font-bold text-white">Helsinki</TableHead>
              <TableHead className="font-bold text-white">Tokio</TableHead>
              <TableHead className="font-bold text-white">Moskova</TableHead>
              <TableHead className="font-bold text-white">New York</TableHead>
              <TableHead className="font-bold text-white">Pariisi</TableHead>
              <TableHead className="font-bold text-white">Nairobi</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow className="bg-green-500 text-white">
              <TableCell className="font-medium">Viikko 1</TableCell>
              <TableCell>2°C</TableCell>
              <TableCell>10°C</TableCell>
              <TableCell>-5°C</TableCell>
              <TableCell>5°C</TableCell>
              <TableCell>7°C</TableCell>
              <TableCell>25°C</TableCell>
            </TableRow>
            <TableRow className="bg-yellow-500 text-white">
              <TableCell className="font-medium">Viikko 2</TableCell>
              <TableCell>3°C</TableCell>
              <TableCell>12°C</TableCell>
              <TableCell>-3°C</TableCell>
              <TableCell>7°C</TableCell>
              <TableCell>9°C</TableCell>
              <TableCell>27°C</TableCell>
            </TableRow>
            <TableRow className="bg-green-500 text-white">
              <TableCell className="font-medium">Viikko 3</TableCell>
              <TableCell>5°C</TableCell>
              <TableCell>15°C</TableCell>
              <TableCell>-1°C</TableCell>
              <TableCell>9°C</TableCell>
              <TableCell>11°C</TableCell>
              <TableCell>29°C</TableCell>
            </TableRow>
            <TableRow className="bg-yellow-500 text-white">
              <TableCell className="font-medium">Viikko 4</TableCell>
              <TableCell>7°C</TableCell>
              <TableCell>17°C</TableCell>
              <TableCell>1°C</TableCell>
              <TableCell>11°C</TableCell>
              <TableCell>13°C</TableCell>
              <TableCell>31°C</TableCell>
            </TableRow>
            <TableRow className="bg-green-500 text-white">
              <TableCell className="font-medium">Viikko 5</TableCell>
              <TableCell>9°C</TableCell>
              <TableCell>19°C</TableCell>
              <TableCell>3°C</TableCell>
              <TableCell>13°C</TableCell>
              <TableCell>15°C</TableCell>
              <TableCell>33°C</TableCell>
            </TableRow>
            <TableRow className="bg-yellow-500 text-white">
              <TableCell className="font-medium">Viikko 6</TableCell>
              <TableCell>11°C</TableCell>
              <TableCell>21°C</TableCell>
              <TableCell>5°C</TableCell>
              <TableCell>15°C</TableCell>
              <TableCell>17°C</TableCell>
              <TableCell>35°C</TableCell>
            </TableRow>
            <TableRow className="bg-green-500 text-white">
              <TableCell className="font-medium">Viikko 7</TableCell>
              <TableCell>13°C</TableCell>
              <TableCell>23°C</TableCell>
              <TableCell>7°C</TableCell>
              <TableCell>17°C</TableCell>
              <TableCell>19°C</TableCell>
              <TableCell>37°C</TableCell>
            </TableRow>
            <TableRow className="bg-yellow-500 text-white">
              <TableCell className="font-medium">Viikko 8</TableCell>
              <TableCell>15°C</TableCell>
              <TableCell>25°C</TableCell>
              <TableCell>9°C</TableCell>
              <TableCell>19°C</TableCell>
              <TableCell>21°C</TableCell>
              <TableCell>39°C</TableCell>
            </TableRow>
            <TableRow className="bg-green-500 text-white">
              <TableCell className="font-medium">Viikko 9</TableCell>
              <TableCell>17°C</TableCell>
              <TableCell>27°C</TableCell>
              <TableCell>11°C</TableCell>
              <TableCell>21°C</TableCell>
              <TableCell>23°C</TableCell>
              <TableCell>41°C</TableCell>
            </TableRow>
            <TableRow className="bg-yellow-500 text-white">
              <TableCell className="font-medium">Viikko 10</TableCell>
              <TableCell>19°C</TableCell>
              <TableCell>29°C</TableCell>
              <TableCell>13°C</TableCell>
              <TableCell>23°C</TableCell>
              <TableCell>25°C</TableCell>
              <TableCell>43°C</TableCell>
            </TableRow>
            <TableRow className="bg-green-500 text-white">
              <TableCell className="font-medium">Viikko 11</TableCell>
              <TableCell>21°C</TableCell>
              <TableCell>31°C</TableCell>
              <TableCell>15°C</TableCell>
              <TableCell>25°C</TableCell>
              <TableCell>27°C</TableCell>
              <TableCell>45°C</TableCell>
            </TableRow>
            <TableRow className="bg-yellow-500 text-white">
              <TableCell className="font-medium">Viikko 12</TableCell>
              <TableCell>23°C</TableCell>
              <TableCell>33°C</TableCell>
              <TableCell>17°C</TableCell>
              <TableCell>27°C</TableCell>
              <TableCell>29°C</TableCell>
              <TableCell>47°C</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
